(window.webpackJsonp=window.webpackJsonp||[]).push([[350],{1645:function(e,t,n){"use strict";n.r(t),n.d(t,"default",function(){return u}),n.d(t,"isUnread",function(){return d}),n.d(t,"Notification",function(){return f}),n.d(t,"Feature",function(){return p});var a=n(365),r=n(366),o=n(401),c=n(375),i=n(378),s=n(367),l=n(13),m=n(0);function u(e){const t=e.loading,n=e.loadingMore,r=e.news,o=e.notificationsLastReadDate,l=e.paging;return a.createElement(i.a,{onRequestClose:e.onClose},a.createElement("div",{className:"notifications-sidebar"},a.createElement("div",{className:"notifications-sidebar-top"},a.createElement("h3",null,Object(m.l)("embed_docs.whats_new")),a.createElement(s.d,{className:"button-tiny",iconProps:{size:12,thin:!0},onClick:e.onClose})),a.createElement("div",{className:"notifications-sidebar-content"},t?a.createElement("div",{className:"text-center"},a.createElement(c.a,{className:"big-spacer-top",timeout:200})):r.map((e,t)=>a.createElement(f,{key:e.publicationDate,notification:e,unread:d(t,e.publicationDate,o)}))),!t&&l&&l.total>r.length&&a.createElement("div",{className:"notifications-sidebar-footer"},a.createElement("div",{className:"spacer-top note text-center"},a.createElement("a",{className:"spacer-left",href:"#",onClick:e.fetchMoreFeatureNews},Object(m.l)("show_more")),n&&a.createElement(c.a,{className:"text-bottom spacer-left position-absolute"})))))}function d(e,t,n){return n?Object(l.c)(t,n)>0:e<1}function f(e){let t=e.notification,n=e.unread;return a.createElement("div",{className:r("notifications-sidebar-slice",{unread:n})},a.createElement("h4",null,a.createElement(o.a,{date:t.publicationDate,long:!1})),t.features.map((e,t)=>a.createElement(p,{feature:e,key:t})))}function p(e){let t=e.feature;return a.createElement("div",{className:"feature"},a.createElement("ul",{className:"categories spacer-bottom"},t.categories.map(e=>a.createElement("li",{key:e.name,style:{backgroundColor:e.color}},e.name))),a.createElement("span",null,t.description),t.readMore&&a.createElement("a",{className:"learn-more",href:t.readMore,rel:"noopener noreferrer nofollow",target:"_blank"},Object(m.l)("learn_more")))}},378:function(e,t,n){"use strict";n.d(t,"a",function(){return c});var a=n(365),r=n(405),o=n(366);function c(e){return a.createElement(r,Object.assign({className:o("modal",{"modal-small":"small"===e.size,"modal-medium":"medium"===e.size,"modal-large":"large"===e.size}),isOpen:!0,overlayClassName:o("modal-overlay",{"modal-no-backdrop":e.noBackdrop})},e))}r.setAppElement("#content")},401:function(e,t,n){"use strict";n.d(t,"b",function(){return i}),n.d(t,"a",function(){return s});var a=n(365),r=n(359),o=n(13);const c={year:"numeric",month:"short",day:"2-digit"},i={year:"numeric",month:"long",day:"numeric"};function s(e){let t=e.children,n=e.date,s=e.long;return a.createElement(r.FormattedDate,Object.assign({value:Object(o.g)(n)},s?i:c),t)}},505:function(e,t,n){var a;
/*!
  Copyright (c) 2015 Jed Watson.
  Based on code that is Copyright 2013-2015, Facebook, Inc.
  All rights reserved.
*/
/*!
  Copyright (c) 2015 Jed Watson.
  Based on code that is Copyright 2013-2015, Facebook, Inc.
  All rights reserved.
*/
!function(){"use strict";var r=!("undefined"==typeof window||!window.document||!window.document.createElement),o={canUseDOM:r,canUseWorkers:"undefined"!=typeof Worker,canUseEventListeners:r&&!(!window.addEventListener&&!window.attachEvent),canUseViewport:r&&!!window.screen};void 0===(a=function(){return o}.call(t,n,t,e))||(e.exports=a)}()}}]);
//# sourceMappingURL=350.m.c86f1795.chunk.js.map